### ISSUE TITLE
docker-sync

### ISSUE THREAD

**Issue by KCErb** [paulcsmith/up#33]
What are your thoughts on using `up` with `docker-sync` (http://docker-sync.io/)?

It seems like my `up.yml` could have a line like:

`docker_compose_command: docker-sync-stack start` and then more or less treat everything else as the same. I'm fairly new to docker, up, lucky, etc. so I'm wondering if from a more experienced perspective anyone sees an issue with this kind of approach.

**Comment by KCErb** [comment]
Oh well, I guess that doesn't quite make sense. The above would call `docker-sync-stack start up` which isn't what I want. I guess a fundamental problem is that docker sync calls `start` when docker compose calls `up` which is the name of this project...I'm guessing they're not really compatible then.

**Comment by KCErb** [comment]
Yeah, I know a lot more about docker now the above doesn't make sense. Up has been a great addition to the tooling though! Thanks @paulcsmith!

**Comment by paulcsmith** [comment]
I'm so glad you're finding it useful! And thanks for the feedback!
